### ISSUE TITLE
[Wiki] KDE Frameworks Sonnet "now" supports Voikko

### ISSUE THREAD

**Issue by Huulivoide** [voikko/corevoikko#14]
Begining with version 5.13 that will be released in 6.8.2015 all KDE
applications and any Qt application making use of Sonnet spellchecking
framework will have support for Voikko.

Sonnet's enchant backend has been completely disabled for some time
now and as so no Voikko support has been in KDE as of lately. Instead
of fixing enchant a new plugin using Voikko directly has been added in.

Plugin has been merged in as of today 10.7.2015.
http://quickgit.kde.org/?p=sonnet.git&a=commit&h=fa8c523ec3cc29fca01da1e171a07bd8d71f282f

Please add this to the list of supported applications when you feel it to be
appropriate to do so.

**Comment by hatapitk** [comment]
Thanks! Wiki and http://voikko.puimula.org/sovellukset.html have now been updated to contain this information.
