### ISSUE TITLE
Some specialized bridge words are missing from voikko

### ISSUE THREAD

**Issue by suokko** [voikko/corevoikko#15]
Hello, 

I have noticed that few Finnish words used commonly in the card game called bridge are missing from voikko.

renonssi (noun, from swedish, meaning: no cards in a suit, void in English)
pieti (noun, from swedish, meaning: Under trick(s) in a bid contract, eg down two is kaksi pietiä)
sangi (noun, from swedish, meaning: a bid without a trump suit, no trump in English)
sakaus (noun, from verb sakata, meaning: a card from another suit when can't follow the led suit, discard in English)
maybe too:
singeli (noun, from english/swedish, One card in a suit, singleton in English)
dubbeli (noun, from english/swedish, Two cards in a suit, doubleton in English)

I don't know how much voikko wants to and words that are derived from foreign words and only used in a specialized setting like a single game.

https://www.cs.tut.fi/~jkorpela/bridge/sanasto.html

**Comment by hatapitk** [comment]
We can add words like this as rare words (frequency class 10). Or if there is an interested maintainer for larger special vocabulary (likely not just for bridge but for games & entertainment or something similar) that would be OK as well.

**Comment by suokko** [comment]
I would be a bad maintainer because dyslexia makes correct spelling very hard for me.

Maintaining games & entertainment category would be mostly trusting other people telling about words. For example I have very little knowledge about chess vocabulary even tough bridge and chess share a playing venue in Helsinki. I also played chess for fun in school but our group had no tournament players who would know the special vocabulary.

If you can add the bridge words to voikko it would help me avoiding spelling errors on those words.

Does compound words require something special to appear to the word list?
eg. pietitikki, sangipito, singelilähtö

**Comment by hatapitk** [comment]
Added to Joukahainen as rare words. Whether compound words will be accepted or not depends on the application that uses this data. Usually they will be accepted.
