### ISSUE TITLE
voikko.analyze doesn't return baseform

### ISSUE THREAD

**Issue by ottopoika** [voikko/corevoikko#16]
I would like to convert words to their baseform. If I understood morphological-analysis.txt correctly the analyze method should also have baseform in return value. However it only returns {NUMBER=singular, STRUCTURE==pppppppp, SIJAMUOTO=ulkoolento, CLASS=nimisana}

```java
import java.util.*;
import org.puimula.libvoikko.*;

public class voikkotest {
    public static void main(String[] args)  {
        Voikko voikko = new Voikko("fi");
        List<Analysis> analyses = voikko.analyze("kissalla");
        System.out.println(analyses.get(0));
    }
}
```

**Comment by hatapitk** [comment]
Perhaps you are using the default dictionary present in Linux distributions? Full morphological analysis requires extra information that is included if suomi-malaga is built with VOIKKO_DEBUG=yes. Alternatively you can just download a pre-built "morpho" dictionary from here: http://puimula.org/htp/testing/voikko-snapshot

But indeed, this is badly documented in the source code. Let's fix that...

**Comment by ottopoika** [comment]
I tried with morpho dictionary, but the results where same. Also it didn't seem to matter what path I gave (even non existing ones). I'm using OSX and installed voikko with homebrew.

```java
import java.util.*;
import org.puimula.libvoikko.*;

public class voikkotest {
    public static void main(String[] args)  {
        String dictionaryPath = System.getProperty("user.dir") + "/mor-morpho";
        Voikko voikko = new Voikko("fi", dictionaryPath);
        List<Analysis> analyses = voikko.analyze("kissalla");
        System.out.println(analyses.get(0));
    }
}
```

**Comment by hatapitk** [comment]
The dictionary path passed to the constructor must not point to an individual dictionary but to a directory where dictionaries (one or more) are installed. In this case if you had
<code>
Voikko voikko = new Voikko("fi", "/Library/Spelling/voikko");
</code>
then path to the individual dictionary would be /Library/Spelling/voikko/2/mor-morpho
That is, the directory structure within the dictionary zip files is significant and needs to be preserved.

**Comment by hatapitk** [comment]
And also if you use homebrew that comes with its own dictionary (maybe? I don't know but it seems like that) then it is best to specify in the constructor that you want to use the morpho dictionary instead of the standard dictionary (which would be the default if you just request "fi"). So you should ask for "fi-x-morpho" instead:
<code>
Voikko voikko = new Voikko("fi-x-morpho", "/Library/Spelling/voikko");
</code>

**Comment by ottopoika** [comment]
Thanks. Now I got it working.

**Comment by mthierydydu** [comment]
Tested at changeset `ae975dd` with 2.2 dictionaries from http://puimula.org/htp/testing/voikko-snapshot/:

I was also missing the base forms: using the **morpho** dictionary when instanciating `Voikko` worked for me: `new Voikko("fi-x-morpho", ...)`
