### ISSUE TITLE
OS X, homebrew, enchant ja libvoikko?

### ISSUE THREAD

**Issue by heikkil** [voikko/corevoikko#23]
Olen mielestäni käynyt nyt kaikki mahdollliset yhdistelmät saada enchant tunnistaman suomen kieltä OSX:än alla. Vihjeitä tarvitsisin. Tavoitteena on käyttää oikolukua emacsissa käyttäen wcheck-koodia, joka kutsuu enchantia.

Ainakin tämän repon wikin ja enchantin dokumentaation mukaan voikko on tuettu ja pitäisi toimia. libvoikkoa päivitetään jatkuvasti homebrewssä ja voikkospell toimii komentorivillä. Olen koettanut luoda symbolisiä linkkejä eri libvoikon hakemistotasoille hakemistoon ~/.enchant, mutta mikään ei auta. Enchant vaan sitkeästi ilmoittaa "Couldn't create a dictionary for fi".

Myöskään VoikkoSpellService-appin asentaminen ei auta. Perus emacs ei OS X:n systeemipalveluista paljoa tiedä.

Olisiko enchantin tukeminen unohtunut matkan varrella?

**Comment by hatapitk** [comment]
Kyllä Enchantin pitäisi edelleen toimia, toimii ainakin minulla vielä Debianissa. Mutta jos Enchant on käännetty järjestelmässä, jossa ei ole libvoikkoa, Enchantin Voikko-tuki on todennäköisesti jäänyt pois, eikä silloin riitä, että libvoikko asennetaan jälkikäteen. Tämän voi tarkistaa katsomalla, mitä tiedostoja tuo enchant-paketti asentaa. Sieltä pitäisi löytyä ainakin seuraavat (nämä polut listattu Linuxissa, joten pitää hiukan soveltaa):
<pre>
/usr/lib/x86_64-linux-gnu/libenchant.so.1.6.0
/usr/lib/x86_64-linux-gnu/libenchant.so.1
/usr/lib/x86_64-linux-gnu/enchant/libenchant_aspell.so
/usr/lib/x86_64-linux-gnu/enchant/libenchant_hspell.so
/usr/lib/x86_64-linux-gnu/enchant/libenchant_ispell.so
/usr/lib/x86_64-linux-gnu/enchant/libenchant_myspell.so
/usr/lib/x86_64-linux-gnu/enchant/libenchant_voikko.so
</pre>

**Comment by heikkil** [comment]
Kiitos ohjeista.

Enchantin englanninkielinen tarkistus toimii ja minulla on aspell asennettuna, joten hakemistosta `/usr/local/Cellar/enchant/1.6.0/lib/enchant` löytyykin tiedostot `libenchant_aspell.a` ja   `libenchant_aspell.so`. Mitään muuta siellä ei olekaan. Ja nyt kun osaan katsoa, niin enchantin brewresepti listaa vain aspellin riippuvuudeksi.

Nyt pitäisi sitten saada joku lisäämään resepti tai opetella tekemään se itse. Vapaaehtoisia?
Avaan nyt ainakin ensin tiketin homebrewn repossa.

**Comment by algoni** [comment]
Homebrew-versio enchantista ei tosiaan vieläkään tue Voikkoa, mutta enchantin asentaminen erikseen [http://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz](http://www.abisource.com/downloads/enchant/1.6.0/enchant-1.6.0.tar.gz) toimii kyllä. Tämän asentamisen jälkeen löytyy hakemistosta `/usr/local/lib/enchant` OSX:llä tiedostot

```
libenchant_aspell.a
libenchant_aspell.la
libenchant_aspell.so
libenchant_ispell.a
libenchant_ispell.la
libenchant_ispell.so
libenchant_myspell.a
libenchant_myspell.la
libenchant_myspell.so
libenchant_voikko.a
libenchant_voikko.la
libenchant_voikko.so
```

ja sain tällä tarkistuksen toimimaan vimissä.

**Comment by hatapitk** [comment]
Kiitoksia asian selvittelystä! Eli mitään varsinaista Voikon puolella korjattavissa olevaa bugia tässä ei taida olla, kysymys on vain siitä kuinka tuo Homebrew-versio Enchantista on konfiguroitu. Suljen tämän siis ratkaistuna.

**Comment by heikkil** [comment]
@algoni, kiitos kommentista, jonka ansiosta pääsin eteenpäin. Tässä tarkempia ohjeita muille tumpeloille:

Minulla on homebrewllä asennettu libvoikko, jonka sijainti pitää kertoa enchant kääntäjälle:

    ./configure --with-voikko-prefix=/usr/local/Cellar/libvoikko/4.0.2

    ....
    enchant-1.6.0

	prefix:                         /usr/local
	compiler:                       gcc

	Build Aspell backend:           yes
	Build Ispell backend:           yes
	Build Uspell backend:           no
	Build Hspell backend:           no
	Build Myspell/Hunspell backend: yes
	Build Voikko backend:           yes
	Build Zemberek backend:         no
	Build a relocatable library:	no


    $ make
    $ (sudo) make install

Testausta:

    $ cat > t.txt
    Satu meni saunaan.<cntr-D>
    $ enchant -d fi -a t.txt
    @(#) International Ispell Version 3.1.20 (but really Enchant 1.6.0)
    *
    & mani 5 5: maani, Manu, mania, meni, mansi
    *

Nyt toimii!
