### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by mkoske** [voikko/corevoikko#26]
Hello,

where I can find documentation for libvoikko? I would like to use voikkos spell-checking and hyphen features but I cannot find docs.

**Comment by hatapitk** [comment]
Documentation for the C/C++ API is in the header file, Java API has been documented using Javadoc, Python API with Python documentation comments and .Net API is identical to Java API (you can also browse it online at http://www.puimula.org/htp/testing/voikko-sdk/java/javadoc/)
