### ISSUE TITLE
voikko.h says incorrectly that only Finnish is supported

### ISSUE THREAD

**Issue by rrthomas** [voikko/corevoikko#30]
I understand that Voikko now supports VFST and HFST formats. Therefore, the comments in `voikko.h` stating that only Finnish is supported should be changed or removed.

**Comment by hatapitk** [comment]
Thanks! You are right, the comment must be removed. I have done that and fixed other similar outdated comments in a2bcfdedcf022069bc720c2e72e8153b4934b52a.

**Comment by rrthomas** [comment]
Thanks, that’s great!
