### ISSUE TITLE
Configurable hyphenation character or string (JavaScript)

### ISSUE THREAD

**Issue by Ciantic** [voikko/corevoikko#35]
I would like to set string `&shy;` as a hyphenation character, right now the `hyphenate` function inserts regular `-` but this is not wanted character e.g. when rendering HTML.

`&shy;` is supported by most browsers, this is probably mostly needed on JS side of the library.

**Comment by hatapitk** [comment]
Actually this will not be enough for proper hyphenation on web pages. It will lead to word "vaa'an" to be replaced with "vaa&amp;shy;an" which in turn will be shown as "vaaan" if there is no line break. This is not what most people would expect.
We will need additional boolean parameter to specify whether hyphenation points that lead to context changes should be included or excluded. At this point it is probably best to move the logic to libvoikko core. In fact this complication was one of the reasons why it was not there in the first place. Client code (such as LibreOffice) has hyphenation API that was better served with what is now getHyphenationPattern in our JavaScript API.

**Comment by Ciantic** [comment]
I actually ended up using a getHyphenationPattern like this:

```
let word = "testi";
let pattern = v.getHyphenationPattern(w);
let j = 0;
let newWord = "";
for (const char of pattern) {
    if (char === "-") {
        newWord += "­";
    }
    newWord += w[j];
    j++;
}
console.log(testi);
```

It works for now.

**Comment by hatapitk** [comment]
@Ciantic your implementation that uses getHyphenationPattern seems correct to me. With the latest changes you can do the same with the following, shorter piece of code:
<pre>
let w = "testi";
let newWord = v.hyphenate(w, "&amp;shy;", false);
console.log(newWord);
</pre>

Works with JavaScript, Java and Python.
