### ISSUE TITLE
voikko emacsille?

### ISSUE THREAD

**Issue by spmima** [voikko/corevoikko#45]
Olen koettanut saada suomenkielen kielentarkistusta toimimaan emacsille (linux mint, emacs versio 27) huonolla menestyksellä. tmispell näyttää toimivan oikein komentotulkissa ja lisäsin init.el tiedostoon tmispell sivustolla olleet rivit, mutta emacs herjaa että  "the file /usr/lib/aspell/suomi" can not be opened for reading. Emacs kai preferoi hunspell ennen ispelliä. Olen koettanut kaivella eri keskustelufoorumeita mutta en löydä mistään ohjeista siitä miten voikon saisi tukemaan emacsia. Omassa koneessani abiword, libreoffice ja gedit näyttävät käyttävän voikkoa eli en usko että tiedostoja puuttuisi.
nimim. "epätoivoinen eläkeläinen jolla deadline pukkaa ensi lauantaiksi".

**Comment by spmima** [comment]
tyhmä minä. Aspellille piti tehdä sama kuin ispellille eli luoda linkki tmispelliin. Sen jälkeen emacsin kielentarkastus toimii.

**Comment by tlikonen** [comment]
@spmima, Emacsissa voi käyttää myös Wcheck-modea, jonka avulla Voikko toimii myös `enchant`- tai `voikkospell`-komentojen avulla.

https://github.com/tlikonen/wcheck-mode
