### ISSUE TITLE
Lua 5.3 bindings for libvoikko; Voikko mailing list?

### ISSUE THREAD

**Issue by ahomansikka** [voikko/corevoikko#46]
I have made Lua (version 5.3) bindings for Libvoikko.

https://github.com/ahomansikka/lualibvoikko
It should have everyhing except grammar checking.

Also, it seems that the Finnish Voikko mailing list does not work any more.

**Comment by hatapitk** [comment]
Thanks! Lua bindings mentioned in the Wiki and mailing list re-started.
