### ISSUE TITLE
Voikko JS build is not working with new Emscripten version (> 1.39.20)

### ISSUE THREAD

**Issue by vepasto** [voikko/corevoikko#48]
With the new Emscripten after build everything seems right and it loads data files, but when I run `libvoikko.init('fi')`, it throws error `getpwuid_r: TODO`.

With Emscripten > 1.39.20

Command
slightly modified `build.sh preload`

The error I got
`libvoikko.init('fi')` throws `getpwuid_r: TODO`

I managed to get it working on Emscripten `1.39.4`

**Comment by hatapitk** [comment]
Thanks! Might be fixed with 763b79f3b55a11f4ec8a0ba3cb89ccf5f0052fa2. I tested with Emscripten 1.39.8 and not the latest release though so there could be something else that needs to be fixed. I will test that later.

**Comment by hatapitk** [comment]
Tested with Emscripten 2.0.11. Builds fine and qunit tests pass on Firefox and Chrome. So indeed fixed now on master.
