### ISSUE TITLE
4.3: build fails

### ISSUE THREAD

**Issue by kloczek** [voikko/corevoikko#49]
gcc 11.0.1
```
[tkloczko@barrel libvoikko-4.3]$ make
make  all-recursive
make[1]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libvoikko-4.3'
Making all in src
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/libvoikko-4.3/src'
/bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..     -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fdata-sections -ffunction-sections -fno-rtti -fvisibility=hidden -Wall -Werror -pedantic -c -o fst/Transducer.lo fst/Transducer.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none -fdata-sections -ffunction-sections -fno-rtti -fvisibility=hidden -Wall -Werror -pedantic -c fst/Transducer.cpp  -fPIC -DPIC -o fst/.libs/Transducer.o
In file included from /usr/include/c++/11/ext/string_conversions.h:41,
                 from /usr/include/c++/11/bits/basic_string.h:6595,
                 from /usr/include/c++/11/string:55,
                 from ./fst/Transducer.hpp:36,
                 from fst/Transducer.cpp:30:
/usr/include/c++/11/cstdlib:151:11: error: ‘malloc’ has not been declared in ‘::’
  151 |   using ::malloc;
      |           ^~~~~~
/usr/include/c++/11/cstdlib:164:11: error: ‘realloc’ has not been declared in ‘::’
  164 |   using ::realloc;
      |           ^~~~~~~
make[2]: *** [Makefile:1335: fst/Transducer.lo] Error 1
make[2]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libvoikko-4.3/src'
make[1]: *** [Makefile:437: all-recursive] Error 1
make[1]: Leaving directory '/home/tkloczko/rpmbuild/BUILD/libvoikko-4.3'
```

**Comment by kloczek** [comment]
Just teste all patchech already commited for libvoikko and none of them are fixing that issue.

BTW two suggestions:
- separate libvoikko into own repository https://github.com/voikko/libvoikko (clone current repo -> remove from clone everything else than libvoikko -> move libvoikko/ content directory above to preserve all past changes history)
- use just `<version>`  instead `rel-voikko-<version>` to allow easier use gitlab autogenerated from git tag tar balls to test patches added after release

**Comment by kloczek** [comment]
Closing.
Thart is the effect caused by autoconf. 2.70.
Upgrade to autoconf 2.71 fixes reported issue :)

PS. Please consider suggestions which mentioneg here.

**Comment by hatapitk** [comment]
Great to hear that you figured it out as I could not reproduce this bug (gcc 11.0.0 in Debian sid). But I removed autoconf tests for malloc and realloc as I guess they have been responsible for this issue and seems like we don't even need them anymore.

About your suggestion: I would like to do that but there is one issue that would need to be resolved first: we have integration tests for libvoikko and voikko-fi which cannot reasonably be split to different repositories. This is because some features may move from libvoikko to voikko-fi when we improve the dictionary file format. And it is much easier to work with this code when those tests can be added in the same commit with actual change in libvoikko or voikko-fi. So for now I will keep them in the same repository. It should be possible to mirror individual subdirectories in a separate repository if you only care about master branch.

**Comment by kloczek** [comment]
> But I removed autoconf tests for malloc and realloc as I guess they have been responsible for this issue and seems like we don't even need them anymore.

Everything goes OK on already tagged source tree state so it it is needed you may restore that part :P

> About your suggestion: I would like to do that but there is one issue that would need to be resolved first: we have integration tests for libvoikko and voikko-fi which cannot reasonably be split to different repositories

Hmm .. and is not possible to separate tests for libvoikko and voikko-fi?
My understanding ii it only current state and theoretically/in future it will be possible to split those test units? :) Am I right?
You know .. no rush.
My experience says that keeping more than one (effective) project in single VCS repo always ends badly :P
PS. Similar issue is with for example with whole SELinux tooling .. which is IMO hellish :)
