### ISSUE TITLE
Voikko on RHEL

### ISSUE THREAD

**Issue by ViitasaariVille** [voikko/corevoikko#53]
Hi, I was trying to install Voikko on RHEL 8 by running yum install python3-libvoikko and pip3 install libvoikko. However, I could not get it to work. The error I was getting was "undefined symbol: voikkoInsertHyphensCstr". However, when I installed Voikko (both the core library and the python API) from Github source, it's working on RHEL 8. Just to let you know. I didn't debug further. And great tool!

**Comment by hatapitk** [comment]
Thanks for the report. This can happen if version of libvoikko is older than python-libvoikko. As you confirmed this does not happen when using upstream source code the issue must be either in RHEL packaging or your local installation.
