### ISSUE TITLE
Vuotias and Vuotiaana

### ISSUE THREAD

**Issue by jrv-hub** [voikko/corevoikko#57]
40-vuotias 30-vuotiaana are rejected
 but year written without numbers, like next
neljäkymmentävuotias and kolmekymmentävuotiaana 
are accepted.

References:
https://kielitoimistonohjepankki.fi/ohje/ajanilmaukset-ika-ja-syntymapaivat-numeroin/
https://kielitoimistonohjepankki.fi/ohje/yhdysmerkki-yhdyssanassa-jossa-lyhenne-numero-tms-tosi-tv-f1-kilpailu/

**Comment by ahomansikka** [comment]
Näyttää toimivan Ubuntussa

$ echo 40-vuotias |voikkospell -m
C: 40-vuotias
A(40-vuotias):1:BASEFORM=40-vuotias
A(40-vuotias):1:CLASS=laatusana
A(40-vuotias):1:COMPARISON=positive
A(40-vuotias):1:FSTOUTPUT=[Lu]40-[Bc][Ll][Xp]vuotias[X]vuotia[Sn][Ny]s
A(40-vuotias):1:NUMBER=singular
A(40-vuotias):1:SIJAMUOTO=nimento
A(40-vuotias):1:STRUCTURE==qq-=ppppppp
A(40-vuotias):1:WORDBASES=+40+-+vuotias(vuotias)
$ echo 30-vuotiaana |voikkospell -m
C: 30-vuotiaana
A(30-vuotiaana):1:BASEFORM=30-vuotias
A(30-vuotiaana):1:CLASS=laatusana
A(30-vuotiaana):1:COMPARISON=positive
A(30-vuotiaana):1:FSTOUTPUT=[Lu]30-[Bc][Ll][Xp]vuotias[X]vuotiaa[Ses][Ny]na
A(30-vuotiaana):1:NUMBER=singular
A(30-vuotiaana):1:SIJAMUOTO=olento
A(30-vuotiaana):1:STRUCTURE==qq-=ppppppppp
A(30-vuotiaana):1:WORDBASES=+30+-+vuotias(vuotias)

**Comment by jrv-hub** [comment]
In Ferora 39 voikkospell shows same results.

```
$ echo 40-vuotias |voikkospell -m 
C: 40-vuotias
A(40-vuotias):1:BASEFORM=40-vuotias
A(40-vuotias):1:CLASS=laatusana
A(40-vuotias):1:COMPARISON=positive
A(40-vuotias):1:FSTOUTPUT=[Lu]40-[Bc][Ll][Xp]vuotias[X]vuotia[Sn][Ny]s
A(40-vuotias):1:NUMBER=singular
A(40-vuotias):1:SIJAMUOTO=nimento
A(40-vuotias):1:STRUCTURE==qq-=ppppppp
A(40-vuotias):1:WORDBASES=+40+-+vuotias(vuotias)
$  echo 30-vuotiaana |voikkospell -m
C: 30-vuotiaana
A(30-vuotiaana):1:BASEFORM=30-vuotias
A(30-vuotiaana):1:CLASS=laatusana
A(30-vuotiaana):1:COMPARISON=positive
A(30-vuotiaana):1:FSTOUTPUT=[Lu]30-[Bc][Ll][Xp]vuotias[X]vuotiaa[Ses][Ny]na
A(30-vuotiaana):1:NUMBER=singular
A(30-vuotiaana):1:SIJAMUOTO=olento
A(30-vuotiaana):1:STRUCTURE==qq-=ppppppppp
A(30-vuotiaana):1:WORDBASES=+30+-+vuotias(vuotias)
nipsu@isla211:~$ 

```

The problem is in LibreOffice Writer.

![image](https://github.com/voikko/corevoikko/assets/162116291/d85a6491-7c75-4f05-87ad-b76c2f1eb729)

**Comment by hatapitk** [comment]
This is a known bug in LibreOffice. I reported it years ago: https://bugs.documentfoundation.org/show_bug.cgi?id=90578 Unfortunately they consider it to be a bug in ICU. I think I reported it there as well, without success.

As you found out Voikko handles this correctly so I have to close this as downstream issue.
